name: CI
on: [push]
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: "1.14"
    - uses: actions/checkout@v1
    - name: Check formatting
      run: diff -u <(echo -n) <(gofmt -d .)
    - name: Run go test
      run: go test -v
